title: Elixir School
email: sean@seancallan.com
description: Lessons in the Fundamentals of Elixir
baseurl: '/'
url: 'http://elixirschool.com' # the base hostname & protocol for your site
twitter_username: doomspork
github_username: doomspork

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - kramdown
  - jekyll-assets
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

assets:
  compress:
    css:  sass
    js:   uglifier
